language: node_js
node_js:
  - "stable"

os:
  - osx

env:
  - ISTANBUL_REPORT_DIR=coverage ISTANBUL_REPORTERS=lcovonly CASHER_TIME_OUT=54000

cache:
  directories:
  - node_modules
  - app/node_modules
  - build
  - thirdparty

before_install:
  - npm install --only=dev
  - node_modules/.bin/gulp dependencies

install: PKG_CONFIG_PATH=$(pwd)/thirdparty/opencv/lib/pkgconfig npm install

script:
  - npm run coverage
  - npm run e2e -- --timeout=30000
  - bash <(curl -s https://codecov.io/bash) -s coverage -f *.info

deploy:
  provider: script
  script: npm build --x64
