language: node_js
node_js:
  - "stable"

os:
  - osx

env:
  - ISTANBUL_REPORT_DIR=coverage ISTANBUL_REPORTERS=lcovonly CASHER_TIME_OUT=54000

cache:
  directories:
  - /usr/local/Cellar/opencv3
  - /usr/local/Cellar/tesseract
  - node_modules
  - app/node_modules

before_install:
  - brew update
  - brew tap homebrew/science
  - brew install opencv3 --without-python --without-numpy --without-test
  - brew link opencv3 --force
  - ln -s /usr/local/Cellar/opencv3/3.1.0_4/share/OpenCV/3rdparty/lib/libippicv.a /usr/local/lib/
  - brew install poppler
  - brew install tesseract --all-languages
  - brew link tesseract --force

install: PKG_CONFIG_PATH=$(pwd)/thirdparty/opencv/lib/pkgconfig npm install

script:
  - npm run coverage
  - npm run e2e -- --timeout=30000
  - bash <(curl -s https://codecov.io/bash) -s coverage -f *.info
