language: node_js
node_js:
  - "stable"

os:
  - osx

env:
  - ISTANBUL_REPORT_DIR=coverage ISTANBUL_REPORTERS=lcovonly CASHER_TIME_OUT=54000

cache:
  directories:
  - node_modules
  - app/node_modules
  - build
  - thirdparty

before_cache:
  - rm -f build/tessdata-master

before_install:
  - mv app/npm-shrinkwrap.json app/.npm-shrinkwrap.json
  - npm install --only=dev
  - node_modules/.bin/gulp dependencies
  - mv app/.npm-shrinkwrap.json app/npm-shrinkwrap.json

install: PKG_CONFIG_PATH=$(pwd)/thirdparty/opencv/lib/pkgconfig npm install

script:
  - npm run coverage
  - npm run e2e -- --timeout=30000
  - bash <(curl -s https://codecov.io/bash) -s coverage -f *.info

deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
